apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspedia-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: newspedia
  template:
    metadata:
      labels:
        app: newspedia
    spec:
      containers:
      - name: rails-app
        image: username/kubernetes-rails-example:latest
        ports:
        - containerPort: 3000
