version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/newspedia
    ports:
      - "3000:3000"
    depends_on:
      - db

# version: '3'
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/newspedia
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - chrome
#     stdin_open: true
#     tty: true
#   chrome:
#     image: selenium/standalone-chrome:3.141.59-dubnium
#     ports:
#       - 4444:4444


# version: '3'
# services:
#   db:
#     image: postgres
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgresql-data:/var/lib/postgresql/data
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     tty: true
#     stdin_open: true
#     volumes:
#       - .:/newspedia
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
# volumes:
#   postgresql-data:
#     driver: local
